name: task_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: ^1.1.6
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  badges: ^3.0.2
  sizer: ^2.0.15
  intl: ^0.17.0
  syncfusion_flutter_datepicker: 20.4.44
  flutter: 
    sdk: flutter



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/Lexend Deca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend Deca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend Deca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend Deca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend Deca/LexendDeca-SemiBold.ttf
          weight: 600
  uses-material-design: true

